### ISSUE TITLE
MIQ Fine1: physical-infrastructure-menu-not-shown-by-default

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-providers-lenovo#57]
Hi
Can someone here in this group answer my question at miq forum ?
http://talk.manageiq.org/t/fine-1-physical-infrastructure-menu-not-shown-by-default/2349

I plan to try out xclarity to manage my lenovo(system X) devices. 
I remember earlier version of miq has physical infra available for me to add xclarity provider. 
But in recent version this sub-menu disappeared.

Please advise what I missed.

**Comment by blomquisg** [comment]
Hi @tjyang, 

[This was added](https://github.com/ManageIQ/manageiq-ui-classic/blob/84b5b4504e3e3a7aaea2b8e3c270867e80e9de4e/app/presenters/menu/default_menu.rb#L9) for the Fine release to hide the physical infrastructure menu item.

This means that in order to re-enable the Physical Infrastructure menu item, you can simply add a `:physical_infrastructure: true` setting under the [`:product` section](https://github.com/ManageIQ/manageiq/blob/1cc4ea02fb7842789dfea3853c0a581686149ff1/config/settings.yml#L1014) of the `settings.yml` file.

Hope that helps.

**Comment by tjyang** [comment]
@blomquisg , thanks so much for your pointer.

1.  add  "  :physical_infrastructure: true" per your pointer.
 grep physical_infrastructure   /var/www/miq/vmdb/config/settings.yml
  :physical_infrastructure: true

2. reboot
3. menu is now back
![image](https://cloud.githubusercontent.com/assets/378638/26319071/2f5a878e-3ee3-11e7-88a3-2960c6f2500d.png)
